import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { signIn } from 'next-auth/react';
import { useEffect, useState } from 'react';
import { sendCode } from './api/service';
import ModalAuth from '@/components/modal';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const [isModalShown, setIsModalShown] = useState(false);

	// useEffect(() => {
	// 	if (!isModalShown) {
	// 		setIsModalShown(true);
	// 	}
	// }, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<button
					onClick={() => {
						setIsModalShown(true)
					}}
				>
					Login
				</button>
				{isModalShown && <ModalAuth />}
			</main>
		</>
	);
}
